#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "ms2pip.h"


float* amino_masses;
unsigned short* amino_F;
unsigned short* sptm_mapper;
float ntermmod;


// This function initializes amino acid masses and PTMs from a configuration file generated by Omega
void init_ms2pip(char* amino_masses_fname, char* modifications_fname, char* modifications_fname_sptm) {
    int i;
    int nummods;
    int nummods_sptm;
    float mz;
    int numptm;
    int before;
    int after;

    FILE* f = fopen(modifications_fname, "rt");
    fscanf(f,"%i\n",&nummods);
    fclose(f);

    f = fopen(modifications_fname_sptm, "rt");
    fscanf(f,"%i\n", &nummods_sptm);
    fclose(f);

    //malloc
    amino_masses = (float*) malloc((2 * NUM_AMINO_MASSES + nummods + nummods_sptm) * sizeof(float));
    amino_F = (unsigned short*) malloc((2 * NUM_AMINO_MASSES + nummods + nummods_sptm) *
                                       sizeof(unsigned short));
    sptm_mapper = (unsigned short*) malloc((2 * NUM_AMINO_MASSES + nummods + nummods_sptm) * sizeof(unsigned short));

    f = fopen(amino_masses_fname, "rt");
    for (i = 0; i < NUM_AMINO_MASSES; i++) {
        fscanf(f, "%f\n", &amino_masses[i]);
        amino_F[i] = (unsigned short)(amino_masses[i] - 57.021464);
    }
    fscanf(f, "%f\n", &ntermmod);
    fclose(f);

    for (i = 0; i < NUM_AMINO_MASSES; i++) {
        amino_masses[NUM_AMINO_MASSES + i] = amino_masses[i];
        amino_F[NUM_AMINO_MASSES + i] = amino_F[i];
    }

    // TODO: de-duplicate parser!
    f = fopen(modifications_fname_sptm, "rt");
    fscanf(f, "%i\n", &nummods_sptm);
    for (i = 0; i < nummods_sptm; i++) {
        fscanf(f, "%f,%i,%i,%i\n", &mz, &numptm, &before, &after);
        sptm_mapper[after] = before;
        sptm_mapper[after] = before;
        if (after > NUM_AMINO_MASSES - 1) {
            if (before < 0) { // n,c-term
                amino_masses[after] = mz;
            } else {
                amino_masses[after] = amino_masses[before] + mz;
                amino_F[after] =
                    (unsigned short)(amino_masses[before] + mz - 57.021464);
            }
        }
    }
    fclose(f);

    f = fopen(modifications_fname, "rt");
    fscanf(f, "%i\n", &nummods);
    for (i = 0; i < nummods; i++) {
        fscanf(f, "%f,%i,%i,%i\n", &mz, &numptm, &before, &after);
        // SDMOX
        if (after > NUM_AMINO_MASSES - 1) {
            if (before < 0) { // n,c-term
                amino_masses[after] = mz;
            } else {
                amino_masses[after] = amino_masses[before] + mz;
                amino_F[after] =
                    (unsigned short)(amino_masses[before] + mz - 57.021464);
            }
        }
    }
    fclose(f);
}
